name: Node/Yarn CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run Tests
        uses: borales/actions-yarn@v2.0.0
        env:
          CI: true
        with:
          cmd: test
      - name: Run Build
        uses: borales/actions-yarn@v2.0.0
        env:
          CI: true
        with:
          cmd: build
